---
blank_issues_enabled: true
contact_links:
  - name: ğŸ™‹ğŸ¾ Question
    about: Use this to ask a question about this project
    url: https://github.com/orgs/stackabletech/discussions/new?category=q-a
